services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - empdir_db:/var/opt/mssql/data
    user: root
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db,1433;Database=empdir;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      Jwt__Key: supersecret_dev_key_change_me_32chars
      Jwt__Issuer: EmployeeDirectory
      Jwt__Audience: EmployeeDirectory.Clients
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        echo '🔄 Ожидание готовности SQL Server...' &&
        sleep 30 &&
        echo '✅ SQL Server готов!' &&
        echo '🚀 Можно запускать Android приложение!' &&
        echo '🎉 Сервер полностью готов!' &&
        dotnet EmployeeDirectory.Api.dll
      "

volumes:
  empdir_db:
    driver: local

